site_name: Wagtail Advanced Form Builder
nav:
    - Home: index.md
    - Getting started:
        - Installation: getting_started/installing.md
        - Out of the box: getting_started/out_of_the_box.md
    - Contributing:
        - How to: contributing/contributing.md
theme:
    name: readthedocs
    highlightjs: true
extra_css: [extra.css]
